export const cases = [
	{
		'Case No': '#2354',
		'Case Type': 'Active',
		Status: 'In Progress',
		'Client Name': 'John Doe',
		'Date Created': '06-08-2023',
		'Bicycle Health': 80,
		Action: null,
	},
	{
		'Case No': '#2355',
		'Case Type': 'Passive',
		Status: 'Closed',
		'Client Name': 'Jane Smith',
		'Date Created': '05-08-2023',
		'Bicycle Health': 60,
		Action: null,
	},
	{
		'Case No': '#2356',
		'Case Type': 'Active',
		Status: 'Open',
		'Client Name': 'Michael Johnson',
		'Date Created': '04-08-2023',
		'Bicycle Health': 95,
		Action: null,
	},
	{
		'Case No': '#2357',
		'Case Type': 'Passive',
		Status: 'Closed',
		'Client Name': 'Clark kent',
		'Date Created': '10-08-2023',
		'Bicycle Health': 34,
		Action: null,
	},
	{
		'Case No': '#2358',
		'Case Type': 'Passive',
		Status: 'In Progress',
		'Client Name': 'Bruce Wayne',
		'Date Created': '10-08-2023',
		'Bicycle Health': 43,
		Action: null,
	},
];
